### ISSUE TITLE
IETF status?

### ISSUE THREAD

**Issue by vanderlee** [authindicators/rfc-brand-indicators-for-message-identification#10]
I can't find this draft in the IETF tracker. Is this still being actively pursued?
Which email clients currently support BIMI?

**Comment by thede** [comment]
Hi Martijn, 
This is being actively pursued.  We anticipate revising this draft substantially during the next two months.  

If you have comments, we’d love to hear them.  

Thede


--
Thede Loder
Chair, Authindicators Working Group (BIMI) 
Senior Director, Product. Agari Data, Inc. 
M: +1-415-420-8615
E: tloder@agari.com

**Comment by vanderlee** [comment]
Thanks for the reply. Hope this project works out.
