### ISSUE TITLE
BIMI location in the message headers - guaranteed  DKIM break

### ISSUE THREAD

**Issue by Lockhead** [authindicators/rfc-brand-indicators-for-message-identification#2]
As soon as a mail already has an BIMI-Location Header that is also included in the DKIM signed headers list, the MTA that replaces this header will break DKIM and a MUA can not validate DKIM anymore.

**Comment by tzink7** [comment]
BIMI-Location should not be included in the message headers. If it is, the MTA should either strip it or rename it. If DKIM-signed, then any downstream agent that tries to reverify DKIM will not be able to.

**Comment by Lockhead** [comment]
But the wording in the Document currently suggests that this is a possability. I would suggest that the wording should be changed to a more strict handling, like "if a BIMI location header already exists and there is no BIMI entry in the Authentication-Results Header, it is considered a BIMI fail."

**Comment by Lockhead** [comment]
closing this, as I try to remark this wis the pull request #6
