### ISSUE TITLE
Typo in draft-brand-indicators-for-message-identification

### ISSUE THREAD

**Issue by toddherr** [authindicators/rfc-brand-indicators-for-message-identification#24]
In section 5.2 of the subject document, in the ABNF bits for the BIMI-Location header, we see this:

`bimi-evidenced-location-header-uri = "a" *WSP "=" bimi-uri`

That should read instead:

`bimi-evidence-location-header-uri = "a" *WSP "=" bimi-uri`

"bimi-evidence", not "bimi-evidenced"

**Comment by abrotman** [comment]
Fixed in local copy.
