### ISSUE TITLE
Considerations: Vector vs Raster

### ISSUE THREAD

**Issue by abrotman** [authindicators/rfc-brand-indicators-for-message-identification#5]
Consideration to add regarding image file formats (edits and additional info welcome):

A site should consider which image file formats to choose when setting up their BIMI record.  Vector image formats (SVG in this case) have some advantages over raster formats, and vice versa.  One of the advantages of vector formats is superior scaling.  As a sender, there is little control over how your images will be used or displayed.  This could mean that a webmail platform could use the 32x32 image, and attempt to fill a space better suited for 128x128.  If the sender were to choose SVG, the image should scale correctly, while a raster image would likely become pixelated or blocky.  Another use case could be that the MUA might "pop" the logo as the mouse cursor moves over that message.  The SVG image would similarly retain its intended shape without blurring.  One might choose a raster image format for better support for older browsers or MUAs.  The tools for altering raster images have been around for much longer, and have more familiarity.  It's important to note in either case, these image files can carry metadata, and the sender should take care to remove any metadata they may not want exposed or that may needlessly bloat the file size.

**Comment by tzink7** [comment]
Makes sense to add this to the spec as part of the considerations.

**Comment by AntiFreeze** [comment]
Added parts of this in two places in the draft, but did not include the strong recommendation for SVG over all other formats - that probably goes better in a FAQ/best practices document than an RFC draft.
